// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210806163836_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ef8db00-c83d-410c-b0d7-9f139c9a51db"),
                            Description = "Canal de DotNetCore",
                            Name = "DotNetCore"
                        },
                        new
                        {
                            Id = new Guid("d2232940-677e-4efd-892c-338d837cbd64"),
                            Description = "Canal de Angular",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("43f9c002-865f-4236-8048-db8f6b57e856"),
                            Description = "Canal de ReactJs",
                            Name = "ReactJs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
